### ISSUE TITLE
Убрать пункт про использование матерных слов и ругательств

### ISSUE THREAD

**Issue by indieveed** [vue-js-ru/code-of-conduct#6]
Пункт "Использование матерных слов и ругательств в любом виде", на мой взгляд, является лишним и необоснованным, так как ограничивает членов сообщества в использовании всех выразительных средств русского языка. Кроме того, в документе, адаптацией которого являются настоящие нормы поведения, про мат ничего не сказано.

**Comment by Perkovec** [comment]
Мат, в каком бы контексте он не использовался, создает неблагоприятную атмосферу в кругу, где общаются специалисты на свои профессиональные темы. Наша задача - создать благоприятную атмосферу, в которой любой разработчик будет чувствовать, что он находится в кругу профессионалов, а не "в подъезде с корешами". И здесь нет места мату, его отсуствие никому и ничему не вредит, а наоборот, учит участников чистой речи. Адаптация - это не равно "перевод" или "копия", мы лишь указываем этим, что за "фундамент" норм поведения взят кодекс поведения Contributor Covenant. Мы имеем право вносить в него поправки, если считаем их необходимыми.
